project = "blackmercury"
labels = {
  env = "dev",
  app = "web"
}
instance_name_prefixes                                          = ["test-"]
zones                                                           = ["us-central1-a", "us-central-1c"]
patch_reboot_config                                             = "ALWAYS"
apt_type                                                        = "DIST"
apt_excludes                                                    = ["python"]
yum_security                                                    = true
yum_minimal                                                     = true
yum_excludes                                                    = ["bash"]
goo_enabled                                                     = true
zypper_categories                                               = ["security"]
windows_update_classifications                                  = ["CRITICAL", "SECURITY", "UPDATE"]
pre_step_linux_exec_step_config_allowed_success_codes           = null
pre_step_linux_exec_step_config_local_path                      = ""
pre_step_windows_exec_step_config_interpreter                   = ""
pre_step_windows_exec_step_config_allowed_success_codes         = null
pre_step_windows_exec_step_config_local_path                    = ""
post_step_linux_exec_step_config_gcs_object_bucket              = ""
post_step_linux_exec_step_config_gcs_object_generation_number   = ""
post_step_linux_exec_step_config_gcs_object_object              = ""
post_step_windows_exec_step_config_interpreter                  = ""
post_step_windows_exec_step_config_gcs_object_bucket            = ""
post_step_windows_exec_step_config_gcs_object_generation_number = ""
post_step_windows_exec_step_config_gcs_object_object            = ""
duration                                                        = "10s"
recurring_schedule_time_zone_id                                 = "America/New_York"
recurring_schedule_time_of_day_hours                            = 0
recurring_schedule_time_of_day_minutes                          = 30
recurring_schedule_time_of_day_seconds                          = 30
recurring_schedule_time_of_day_nanos                            = 20
monthly_week_day_of_month_week_ordinal                          = -1
monthly_week_day_of_month_day_of_week                           = "TUESDAY"
rollout_mode                                                    = "ZONE_BY_ZONE"
rollout_disruption_budget_fixed                                 = 1
